/**
 * API Route: GET /api/learn/dashboard
 * Returns learning content, checklist, and testimonials
 */

import { NextResponse } from 'next/server';
import { createSuccessResponse } from '@/types/api.types';

export async function GET() {
  const learningPath = [
    {
      id: '1',
      title: 'Understanding Credit Applications',
      description: 'Taking the right steps to apply for credit in Canada. Learn about the application process, required documents, and what lenders look for when reviewing your application.',
      category: 'Beginner',
      duration: '2 min',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'Understanding Credit Reports',
      description: 'Equifax vs TransUnion - Learn the differences between Canada\'s two major credit bureaus and how they track your financial history.',
      category: 'Beginner',
      duration: '3-step guide',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      id: '3',
      title: 'Why Your Credit Score Matters',
      description: "Learn what affects your score and what doesn't. Understand the key factors that determine your creditworthiness and financial opportunities.",
      category: 'Beginner',
      duration: '1 min learning card',
      type: 'article',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      id: '4',
      title: 'Building Credit History',
      description: 'Start your credit journey right. Discover proven strategies for building a strong credit foundation from scratch.',
      category: 'Beginner',
      duration: '5 min',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=3M_5oYU-IsU',
      order: 4,
      createdAt: new Date().toISOString(),
    },
    {
      id: '5',
      title: 'Credit Utilization Explained',
      description: 'Keep your usage in check. Learn why the 30% rule matters and how to optimize your credit card balances for maximum score growth.',
      category: 'Beginner',
      duration: '4 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=yq2aS9WF-Tc',
      order: 5,
      createdAt: new Date().toISOString(),
    },
    {
      id: '6',
      title: 'Managing Multiple Credit Cards',
      description: 'Balance your credit portfolio. Master the art of managing multiple cards to maximize rewards while maintaining a healthy credit profile.',
      category: 'Intermediate',
      duration: '6 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
      order: 6,
      createdAt: new Date().toISOString(),
    },
    {
      id: '7',
      title: 'Credit Card Interest Rates 101',
      description: 'Understanding APR and how it affects you. Learn to decode interest rates and avoid costly charges on your credit cards.',
      category: 'Beginner',
      duration: '7 min read',
      type: 'article',
      order: 7,
      createdAt: new Date().toISOString(),
    },
    {
      id: '8',
      title: 'The 5 Factors of Your Credit Score',
      description: 'What lenders look at and why. Deep dive into the five critical components that make up your credit score and their relative importance.',
      category: 'Beginner',
      duration: '8 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=JUb1_t8K40M',
      order: 8,
      createdAt: new Date().toISOString(),
    },
    {
      id: '9',
      title: 'Secured vs Unsecured Credit Cards',
      description: 'Which one is right for you. Compare the pros and cons of secured and unsecured cards to find the best fit for your financial situation.',
      category: 'Beginner',
      duration: '5 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&q=80',
      order: 9,
      createdAt: new Date().toISOString(),
    },
    {
      id: '10',
      title: 'Credit Card Grace Periods',
      description: 'How to avoid paying interest. Master the timing of grace periods to enjoy interest-free credit and save money.',
      category: 'Intermediate',
      duration: '4 min watch',
      type: 'video',
      videoUrl: 'https://www.youtube.com/watch?v=h9cm7_ZRQgk',
      order: 10,
      createdAt: new Date().toISOString(),
    },
    {
      id: '11',
      title: 'Balance Transfer Strategies',
      description: 'Save money on high-interest debt. Learn strategic approaches to transfer balances and reduce interest charges effectively.',
      category: 'Intermediate',
      duration: '10 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
      order: 11,
      createdAt: new Date().toISOString(),
    },
    {
      id: '12',
      title: 'Credit Limit Increases',
      description: 'When and how to ask for more. Discover the right timing and approach to successfully request credit limit increases.',
      category: 'Intermediate',
      duration: '6 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=KnZTinPMgVw',
      order: 12,
      createdAt: new Date().toISOString(),
    },
    {
      id: '13',
      title: 'Credit Bureaus Explained',
      description: 'How they track your financial history. Understand the role of credit bureaus and how they compile your credit information.',
      category: 'Beginner',
      duration: '5 min read',
      type: 'article',
      order: 13,
      createdAt: new Date().toISOString(),
    },
    {
      id: '14',
      title: 'Annual Fees: Worth It or Not?',
      description: 'Calculate if premium cards make sense',
      category: 'Intermediate',
      duration: '7 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?w=800&q=80',
      order: 14,
      createdAt: new Date().toISOString(),
    },
    {
      id: '15',
      title: 'Disputing Credit Report Errors',
      description: 'Fix mistakes that hurt your score',
      category: 'Advanced',
      duration: '12 min guide',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
      order: 15,
      createdAt: new Date().toISOString(),
    },
    {
      id: '16',
      title: 'Building Credit as a Newcomer',
      description: 'Your first steps in Canada',
      category: 'Beginner',
      duration: '9 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
      order: 16,
      createdAt: new Date().toISOString(),
    },
  ];

  const recommendedContent = [
    // First 1-3 Months
    {
      id: '17',
      title: 'Understanding Credit Without Fear',
      description: 'A beginner-friendly introduction to the Canadian credit system',
      category: 'First 1-3 Months',
      duration: '12 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      id: '18',
      title: 'Overview of Canadian Credit',
      description: 'How the credit system works in Canada',
      category: 'First 1-3 Months',
      duration: '15 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=3M_5oYU-IsU',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      id: '19',
      title: 'How Payment History Impacts Your Score',
      description: 'Why paying on time matters most for newcomers',
      category: 'First 1-3 Months',
      duration: '8 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=yq2aS9WF-Tc',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      id: '20',
      title: 'Types of Credit Cards',
      description: 'Understanding secured vs unsecured cards',
      category: 'First 1-3 Months',
      duration: '10 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=JUb1_t8K40M',
      order: 4,
      createdAt: new Date().toISOString(),
    },
    // Next 4-6 Months
    {
      id: '21',
      title: 'Building Credit History',
      description: 'Strategic approaches to establish strong credit',
      category: 'Next 4-6 Months',
      duration: '14 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1450101215322-bf5cd27642fc?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=h9cm7_ZRQgk',
      order: 5,
      createdAt: new Date().toISOString(),
    },
    {
      id: '22',
      title: 'Store vs Financial Credits',
      description: 'Choosing the right credit products for growth',
      category: 'Next 4-6 Months',
      duration: '11 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=KnZTinPMgVw',
      order: 6,
      createdAt: new Date().toISOString(),
    },
    {
      id: '23',
      title: 'Authorized Users Explained',
      description: 'Building credit with someone else\'s card',
      category: 'Next 4-6 Months',
      duration: '9 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
      order: 7,
      createdAt: new Date().toISOString(),
    },
    {
      id: '24',
      title: 'Managing Multiple Cards',
      description: 'Best practices for credit portfolio management',
      category: 'Next 4-6 Months',
      duration: '13 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=3M_5oYU-IsU',
      order: 8,
      createdAt: new Date().toISOString(),
    },
    // 7+ Months (Advanced)
    {
      id: '25',
      title: 'Credit Limit Optimization',
      description: 'When and how to request credit increases',
      category: '7+ Months',
      duration: '12 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=yq2aS9WF-Tc',
      order: 9,
      createdAt: new Date().toISOString(),
    },
    {
      id: '26',
      title: 'Credit Card Rewards Strategies',
      description: 'Maximize benefits while building credit',
      category: '7+ Months',
      duration: '16 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
      videoUrl: 'https://www.youtube.com/watch?v=JUb1_t8K40M',
      order: 10,
      createdAt: new Date().toISOString(),
    },
    {
      id: '27',
      title: 'Credit Score Ranges Explained',
      description: 'What good, fair, and excellent really mean',
      category: 'Beginner',
      duration: '4 min watch',
      type: 'video',
      order: 11,
      createdAt: new Date().toISOString(),
    },
    {
      id: '28',
      title: 'Debt Consolidation Options',
      description: 'Simplify multiple payments',
      category: 'Advanced',
      duration: '14 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&q=80',
      order: 12,
      createdAt: new Date().toISOString(),
    },
    {
      id: '29',
      title: 'Credit Builder Loans',
      description: 'An alternative path to good credit',
      category: 'Intermediate',
      duration: '7 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&q=80',
      order: 13,
      createdAt: new Date().toISOString(),
    },
    {
      id: '30',
      title: 'Cash Back vs Points',
      description: 'Which rewards strategy wins',
      category: 'Intermediate',
      duration: '6 min read',
      type: 'article',
      order: 14,
      createdAt: new Date().toISOString(),
    },
    {
      id: '31',
      title: 'Credit Age and Why It Matters',
      description: 'The benefits of keeping old accounts',
      category: 'Advanced',
      duration: '5 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
      order: 15,
      createdAt: new Date().toISOString(),
    },
    {
      id: '32',
      title: 'Business Credit Cards for Freelancers',
      description: 'Separate business and personal expenses',
      category: 'Advanced',
      duration: '11 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
      order: 16,
      createdAt: new Date().toISOString(),
    },
  ];

  const checklistItems = [
    {
      id: '1',
      title: "Complete beginner's course",
      description: 'This is your core education module which would teach you all you need to know',
      icon: 'book',
      completed: false,
      actionUrl: '/learn/beginners-course',
      order: 1,
    },
    {
      id: '2',
      title: 'Let Creduman analyse your card',
      description: 'Allow Creduman to monitor your credit limit and advise accordingly',
      icon: 'card',
      completed: false,
      actionUrl: '/cards',
      order: 2,
    },
    {
      id: '3',
      title: 'Enable payment reminders',
      description: 'Never miss a due date and protect your score effortlessly.',
      icon: 'bell',
      completed: false,
      actionUrl: '/settings/notifications',
      order: 3,
    },
    {
      id: '4',
      title: 'Set usage alerts',
      description: 'Choose when Creduman warns you about high spending.',
      icon: 'bell',
      completed: false,
      actionUrl: '/settings/alerts',
      order: 4,
    },
    {
      id: '5',
      title: 'Share Your Success Story',
      description: 'Share your success story in 3 months from your first card and earn a bonus!',
      icon: 'award',
      completed: false,
      actionUrl: '/testimonials/share',
      order: 5,
    },
  ];

  const testimonials = [
    {
      id: '1',
      name: 'Jane',
      title: 'Learn how Jane got a good credit limit after moving to Canada',
      description: 'Learn all you need to know about Credit in Canada with Creduman as their credit safety and learning assistant.',
      imageUrl: '/testimonial.svg',
      order: 1,
    },
    {
      id: '2',
      name: 'Michael',
      title: 'How Michael built his credit score from scratch',
      description: "Discover Michael's journey building excellent credit in just 6 months using Creduman's guidance.",
      imageUrl: '/testimonial.svg',
      order: 2,
    },
    {
      id: '3',
      name: 'Sarah',
      title: "Sarah's path to financial freedom",
      description: 'From newcomer to credit expert - Sarah shares her success story with Creduman.',
      imageUrl: '/testimonial.svg',
      order: 3,
    },
    {
      id: '4',
      name: 'David',
      title: 'David improved his score by 150 points',
      description: 'See how David transformed his credit with smart strategies and Creduman\'s tools.',
      imageUrl: '/testimonial.svg',
      order: 4,
    },
    {
      id: '5',
      name: 'Emily',
      title: "Emily's credit building success in Canada",
      description: "A newcomer's guide to establishing strong credit with Creduman's step-by-step help.",
      imageUrl: '/testimonial.svg',
      order: 5,
    },
  ];

  return NextResponse.json(
    createSuccessResponse({
      learningPath,
      recommendedContent,
      checklistItems,
      testimonials,
    }),
    { status: 200 }
  );
}
