/**
 * API Route: GET /api/learn/dashboard
 * Returns learning content, checklist, and testimonials
 */

import { NextResponse } from 'next/server';
import { createSuccessResponse } from '@/types/api.types';

export async function GET() {
  const learningPath = [
    {
      id: '1',
      title: 'Understanding Credit Applications',
      description: 'Taking the right steps',
      category: 'Credit Basics',
      duration: '2 min',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?w=800&q=80',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      id: '2',
      title: 'Understanding Credit Reports',
      description: 'Equifax vs TransUnion',
      category: 'Credit Basics',
      duration: '3-step guide',
      type: 'guide',
      thumbnailUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      id: '3',
      title: 'Why Your Credit Score Matters',
      description: "Learn what affects your score and what doesn't.",
      category: 'Credit Basics',
      duration: '1 min learning card',
      type: 'article',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      id: '4',
      title: 'Building Credit History',
      description: 'Start your credit journey right',
      category: 'Credit Basics',
      duration: '5 min',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80',
      order: 4,
      createdAt: new Date().toISOString(),
    },
    {
      id: '5',
      title: 'Credit Utilization Explained',
      description: 'Keep your usage in check',
      category: 'Credit Basics',
      duration: '4 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80',
      order: 5,
      createdAt: new Date().toISOString(),
    },
    {
      id: '6',
      title: 'Managing Multiple Credit Cards',
      description: 'Balance your credit portfolio',
      category: 'Intermediate',
      duration: '6 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80',
      order: 6,
      createdAt: new Date().toISOString(),
    },
    {
      id: '7',
      title: 'Credit Card Interest Rates 101',
      description: 'Understanding APR and how it affects you',
      category: 'Credit Basics',
      duration: '7 min read',
      type: 'article',
      order: 7,
      createdAt: new Date().toISOString(),
    },
    {
      id: '8',
      title: 'The 5 Factors of Your Credit Score',
      description: 'What lenders look at and why',
      category: 'Credit Basics',
      duration: '8 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
      order: 8,
      createdAt: new Date().toISOString(),
    },
    {
      id: '9',
      title: 'Secured vs Unsecured Credit Cards',
      description: 'Which one is right for you',
      category: 'Credit Basics',
      duration: '5 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&q=80',
      order: 9,
      createdAt: new Date().toISOString(),
    },
    {
      id: '10',
      title: 'Credit Card Grace Periods',
      description: 'How to avoid paying interest',
      category: 'Intermediate',
      duration: '4 min watch',
      type: 'video',
      order: 10,
      createdAt: new Date().toISOString(),
    },
    {
      id: '11',
      title: 'Balance Transfer Strategies',
      description: 'Save money on high-interest debt',
      category: 'Intermediate',
      duration: '10 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80',
      order: 11,
      createdAt: new Date().toISOString(),
    },
    {
      id: '12',
      title: 'Credit Limit Increases',
      description: 'When and how to ask for more',
      category: 'Intermediate',
      duration: '6 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
      order: 12,
      createdAt: new Date().toISOString(),
    },
    {
      id: '13',
      title: 'Credit Bureaus Explained',
      description: 'How they track your financial history',
      category: 'Credit Basics',
      duration: '5 min read',
      type: 'article',
      order: 13,
      createdAt: new Date().toISOString(),
    },
    {
      id: '14',
      title: 'Annual Fees: Worth It or Not?',
      description: 'Calculate if premium cards make sense',
      category: 'Intermediate',
      duration: '7 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1633158829585-23ba8f7c8caf?w=800&q=80',
      order: 14,
      createdAt: new Date().toISOString(),
    },
    {
      id: '15',
      title: 'Disputing Credit Report Errors',
      description: 'Fix mistakes that hurt your score',
      category: 'Advanced',
      duration: '12 min guide',
      type: 'guide',
      thumbnailUrl: 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80',
      order: 15,
      createdAt: new Date().toISOString(),
    },
    {
      id: '16',
      title: 'Building Credit as a Newcomer',
      description: 'Your first steps in Canada',
      category: 'Credit Basics',
      duration: '9 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&q=80',
      order: 16,
      createdAt: new Date().toISOString(),
    },
  ];

  const recommendedContent = [
    {
      id: '17',
      title: 'Soft vs Hard Inquiries',
      description: 'Which ones hurt your score',
      category: 'Credit Basics',
      duration: '20 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80',
      order: 1,
      createdAt: new Date().toISOString(),
    },
    {
      id: '18',
      title: 'What is a Credit Score?',
      description: 'Your financial reputation in three digits',
      category: 'Credit Basics',
      duration: '20 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
      order: 2,
      createdAt: new Date().toISOString(),
    },
    {
      id: '19',
      title: 'How Payment History Impacts Your Score',
      description: 'Why paying on time matters most',
      category: 'Intermediate',
      duration: '2 min read',
      type: 'article',
      order: 3,
      createdAt: new Date().toISOString(),
    },
    {
      id: '20',
      title: 'Credit Card Rewards Programs',
      description: 'Maximize your benefits',
      category: 'Intermediate',
      duration: '8 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80',
      order: 4,
      createdAt: new Date().toISOString(),
    },
    {
      id: '21',
      title: 'Dealing with Debt Collectors',
      description: 'Know your rights and options',
      category: 'Advanced',
      duration: '15 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1450101215322-bf5cd27642fc?w=800&q=80',
      order: 5,
      createdAt: new Date().toISOString(),
    },
    {
      id: '22',
      title: 'Credit Mix and Its Impact',
      description: 'Diversifying your credit profile',
      category: 'Intermediate',
      duration: '5 min read',
      type: 'article',
      order: 6,
      createdAt: new Date().toISOString(),
    },
    {
      id: '23',
      title: 'Authorized Users Explained',
      description: 'Building credit with someone else\'s card',
      category: 'Credit Basics',
      duration: '6 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80',
      order: 7,
      createdAt: new Date().toISOString(),
    },
    {
      id: '24',
      title: 'Student Credit Cards Guide',
      description: 'Best options for building credit early',
      category: 'Credit Basics',
      duration: '10 min read',
      type: 'article',
      order: 8,
      createdAt: new Date().toISOString(),
    },
    {
      id: '25',
      title: 'Credit Card Fraud Protection',
      description: 'Stay safe from identity theft',
      category: 'Advanced',
      duration: '8 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80',
      order: 9,
      createdAt: new Date().toISOString(),
    },
    {
      id: '26',
      title: 'Travel Credit Cards Comparison',
      description: 'Earn points while you explore',
      category: 'Intermediate',
      duration: '12 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
      order: 10,
      createdAt: new Date().toISOString(),
    },
    {
      id: '27',
      title: 'Credit Score Ranges Explained',
      description: 'What good, fair, and excellent really mean',
      category: 'Credit Basics',
      duration: '4 min watch',
      type: 'video',
      order: 11,
      createdAt: new Date().toISOString(),
    },
    {
      id: '28',
      title: 'Debt Consolidation Options',
      description: 'Simplify multiple payments',
      category: 'Advanced',
      duration: '14 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?w=800&q=80',
      order: 12,
      createdAt: new Date().toISOString(),
    },
    {
      id: '29',
      title: 'Credit Builder Loans',
      description: 'An alternative path to good credit',
      category: 'Intermediate',
      duration: '7 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=800&q=80',
      order: 13,
      createdAt: new Date().toISOString(),
    },
    {
      id: '30',
      title: 'Cash Back vs Points',
      description: 'Which rewards strategy wins',
      category: 'Intermediate',
      duration: '6 min read',
      type: 'article',
      order: 14,
      createdAt: new Date().toISOString(),
    },
    {
      id: '31',
      title: 'Credit Age and Why It Matters',
      description: 'The benefits of keeping old accounts',
      category: 'Advanced',
      duration: '5 min watch',
      type: 'video',
      thumbnailUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80',
      order: 15,
      createdAt: new Date().toISOString(),
    },
    {
      id: '32',
      title: 'Business Credit Cards for Freelancers',
      description: 'Separate business and personal expenses',
      category: 'Advanced',
      duration: '11 min read',
      type: 'article',
      thumbnailUrl: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&q=80',
      order: 16,
      createdAt: new Date().toISOString(),
    },
  ];

  const checklistItems = [
    {
      id: '1',
      title: "Complete beginner's course",
      description: 'This is your core education module which would teach you all you need to know',
      icon: 'book',
      completed: false,
      actionUrl: '/learn/beginners-course',
      order: 1,
    },
    {
      id: '2',
      title: 'Let Creduman analyse your card',
      description: 'Allow Creduman to monitor your credit limit and advise accordingly',
      icon: 'card',
      completed: false,
      actionUrl: '/card-dashboard',
      order: 2,
    },
    {
      id: '3',
      title: 'Enable payment reminders',
      description: 'Never miss a due date and protect your score effortlessly.',
      icon: 'bell',
      completed: false,
      actionUrl: '/settings/notifications',
      order: 3,
    },
    {
      id: '4',
      title: 'Set usage alerts',
      description: 'Choose when Creduman warns you about high spending.',
      icon: 'bell',
      completed: false,
      actionUrl: '/settings/alerts',
      order: 4,
    },
    {
      id: '5',
      title: 'Share Your Success Story',
      description: 'Share your success story in 3 months from your first card and earn a bonus!',
      icon: 'award',
      completed: false,
      actionUrl: '/testimonials/share',
      order: 5,
    },
  ];

  const testimonials = [
    {
      id: '1',
      name: 'Jane',
      title: 'Learn how Jane got a good credit limit after moving to Canada',
      description: 'Learn all you need to know about Credit in Canada with Creduman as their credit safety and learning assistant.',
      imageUrl: '/testimonial.svg',
      order: 1,
    },
    {
      id: '2',
      name: 'Michael',
      title: 'How Michael built his credit score from scratch',
      description: "Discover Michael's journey building excellent credit in just 6 months using Creduman's guidance.",
      imageUrl: '/testimonial.svg',
      order: 2,
    },
    {
      id: '3',
      name: 'Sarah',
      title: "Sarah's path to financial freedom",
      description: 'From newcomer to credit expert - Sarah shares her success story with Creduman.',
      imageUrl: '/testimonial.svg',
      order: 3,
    },
    {
      id: '4',
      name: 'David',
      title: 'David improved his score by 150 points',
      description: 'See how David transformed his credit with smart strategies and Creduman\'s tools.',
      imageUrl: '/testimonial.svg',
      order: 4,
    },
    {
      id: '5',
      name: 'Emily',
      title: "Emily's credit building success in Canada",
      description: "A newcomer's guide to establishing strong credit with Creduman's step-by-step help.",
      imageUrl: '/testimonial.svg',
      order: 5,
    },
  ];

  return NextResponse.json(
    createSuccessResponse({
      learningPath,
      recommendedContent,
      checklistItems,
      testimonials,
    }),
    { status: 200 }
  );
}
